(function(){function a(){}function c(a,b){for(var c=a.length;c--;)if(a[c].listener===b)return c;return-1}function b(a){return function(){return this[a].apply(this,arguments)}}var d=a.prototype,e=this,f=e.EventEmitter;d.getListeners=function(a){var b,c,d=this._getEvents();if("object"==typeof a)for(c in b={},d)d.hasOwnProperty(c)&&a.test(c)&&(b[c]=d[c]);else b=d[a]||(d[a]=[]);return b};d.flattenListeners=function(a){var b,c=[];for(b=0;a.length>b;b+=1)c.push(a[b].listener);return c};d.getListenersAsObject=
function(a){var b,c=this.getListeners(a);return c instanceof Array&&(b={},b[a]=c),b||c};d.addListener=function(a,b){var d,h=this.getListenersAsObject(a),f="object"==typeof b;for(d in h)h.hasOwnProperty(d)&&-1===c(h[d],b)&&h[d].push(f?b:{listener:b,once:!1});return this};d.on=b("addListener");d.addOnceListener=function(a,b){return this.addListener(a,{listener:b,once:!0})};d.once=b("addOnceListener");d.defineEvent=function(a){return this.getListeners(a),this};d.defineEvents=function(a){for(var b=0;a.length>
b;b+=1)this.defineEvent(a[b]);return this};d.removeListener=function(a,b){var d,f,e=this.getListenersAsObject(a);for(f in e)e.hasOwnProperty(f)&&(d=c(e[f],b),-1!==d&&e[f].splice(d,1));return this};d.off=b("removeListener");d.addListeners=function(a,b){return this.manipulateListeners(!1,a,b)};d.removeListeners=function(a,b){return this.manipulateListeners(!0,a,b)};d.manipulateListeners=function(a,b,c){var d,f,e=a?this.removeListener:this.addListener;a=a?this.removeListeners:this.addListeners;if("object"!=
typeof b||b instanceof RegExp)for(d=c.length;d--;)e.call(this,b,c[d]);else for(d in b)b.hasOwnProperty(d)&&(f=b[d])&&("function"==typeof f?e.call(this,d,f):a.call(this,d,f));return this};d.removeEvent=function(a){var b,c=typeof a,d=this._getEvents();if("string"===c)delete d[a];else if("object"===c)for(b in d)d.hasOwnProperty(b)&&a.test(b)&&delete d[b];else delete this._events;return this};d.removeAllListeners=b("removeEvent");d.emitEvent=function(a,b){var c,d,f,e,m=this.getListenersAsObject(a);for(f in m)if(m.hasOwnProperty(f))for(d=
m[f].length;d--;)c=m[f][d],!0===c.once&&this.removeListener(a,c.listener),e=c.listener.apply(this,b||[]),e===this._getOnceReturnValue()&&this.removeListener(a,c.listener);return this};d.trigger=b("emitEvent");d.emit=function(a){var b=Array.prototype.slice.call(arguments,1);return this.emitEvent(a,b)};d.setOnceReturnValue=function(a){return this._onceReturnValue=a,this};d._getOnceReturnValue=function(){return this.hasOwnProperty("_onceReturnValue")?this._onceReturnValue:!0};d._getEvents=function(){return this._events||
(this._events={})};a.noConflict=function(){return e.EventEmitter=f,a};"function"==typeof define&&define.amd?define("eventEmitter/EventEmitter",[],function(){return a}):"object"==typeof module&&module.exports?module.exports=a:this.EventEmitter=a}).call(this);
(function(a){function c(b){var c=a.event;return c.target=c.target||c.srcElement||b,c}var b=document.documentElement,d=function(){};b.addEventListener?d=function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent&&(d=function(a,b,d){a[b+d]=d.handleEvent?function(){var b=c(a);d.handleEvent.call(d,b)}:function(){var b=c(a);d.call(a,b)};a.attachEvent("on"+b,a[b+d])});var e=function(){};b.removeEventListener?e=function(a,b,c){a.removeEventListener(b,c,!1)}:b.detachEvent&&(e=function(a,b,c){a.detachEvent("on"+
b,a[b+c]);try{delete a[b+c]}catch(d){a[b+c]=void 0}});b={bind:d,unbind:e};"function"==typeof define&&define.amd?define("eventie/eventie",b):a.eventie=b})(this);
(function(a,c){"function"==typeof define&&define.amd?define(["eventEmitter/EventEmitter","eventie/eventie"],function(b,d){return c(a,b,d)}):"object"==typeof exports?module.exports=c(a,require("wolfy87-eventemitter"),require("eventie")):a.imagesLoaded=c(a,a.EventEmitter,a.eventie)})(window,function(a,c,b){function d(a,b){for(var c in b)a[c]=b[c];return a}function e(a){var b=[];if("[object Array]"===k.call(a))b=a;else if("number"==typeof a.length)for(var c=0,d=a.length;d>c;c++)b.push(a[c]);else b.push(a);
return b}function f(a,b,c){if(!(this instanceof f))return new f(a,b);"string"==typeof a&&(a=document.querySelectorAll(a));this.elements=e(a);this.options=d({},this.options);"function"==typeof b?c=b:d(this.options,b);c&&this.on("always",c);this.getImages();l&&(this.jqDeferred=new l.Deferred);var m=this;setTimeout(function(){m.check()})}function n(a){this.img=a}function g(a){this.src=a;m[a]=this}var l=a.jQuery,h=a.console,p=void 0!==h,k=Object.prototype.toString;f.prototype=new c;f.prototype.options=
{};f.prototype.getImages=function(){this.images=[];for(var a=0,b=this.elements.length;b>a;a++){var c=this.elements[a];"IMG"===c.nodeName&&this.addImage(c);var d=c.nodeType;if(d&&(1===d||9===d||11===d))for(var c=c.querySelectorAll("img"),d=0,e=c.length;e>d;d++)this.addImage(c[d])}};f.prototype.addImage=function(a){a=new n(a);this.images.push(a)};f.prototype.check=function(){function a(q,e){return b.options.debug&&p&&h.log("confirm",q,e),b.progress(q),c++,c===d&&b.complete(),!0}var b=this,c=0,d=this.images.length;
if(this.hasAnyBroken=!1,!d)return this.complete(),void 0;for(var e=0;d>e;e++){var f=this.images[e];f.on("confirm",a);f.check()}};f.prototype.progress=function(a){this.hasAnyBroken=this.hasAnyBroken||!a.isLoaded;var b=this;setTimeout(function(){b.emit("progress",b,a);b.jqDeferred&&b.jqDeferred.notify&&b.jqDeferred.notify(b,a)})};f.prototype.complete=function(){var a=this.hasAnyBroken?"fail":"done";this.isComplete=!0;var b=this;setTimeout(function(){if(b.emit(a,b),b.emit("always",b),b.jqDeferred)b.jqDeferred[b.hasAnyBroken?
"reject":"resolve"](b)})};l&&(l.fn.imagesLoaded=function(a,b){return(new f(this,a,b)).jqDeferred.promise(l(this))});n.prototype=new c;n.prototype.check=function(){var a=m[this.img.src]||new g(this.img.src);if(a.isConfirmed)return this.confirm(a.isLoaded,"cached was confirmed"),void 0;if(this.img.complete&&void 0!==this.img.naturalWidth)return this.confirm(0!==this.img.naturalWidth,"naturalWidth"),void 0;var b=this;a.on("confirm",function(a,c){return b.confirm(a.isLoaded,c),!0});a.check()};n.prototype.confirm=
function(a,b){this.isLoaded=a;this.emit("confirm",this,b)};var m={};return g.prototype=new c,g.prototype.check=function(){if(!this.isChecked){var a=new Image;b.bind(a,"load",this);b.bind(a,"error",this);a.src=this.src;this.isChecked=!0}},g.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)},g.prototype.onload=function(a){this.confirm(!0,"onload");this.unbindProxyEvents(a)},g.prototype.onerror=function(a){this.confirm(!1,"onerror");this.unbindProxyEvents(a)},g.prototype.confirm=
function(a,b){this.isConfirmed=!0;this.isLoaded=a;this.emit("confirm",this,b)},g.prototype.unbindProxyEvents=function(a){b.unbind(a.target,"load",this);b.unbind(a.target,"error",this)},f});(function(a){function c(b){"string"===typeof b.data&&(b.data={keys:b.data});if(b.data&&b.data.keys&&"string"===typeof b.data.keys){var c=b.handler,e=b.data.keys.toLowerCase().split(" ");b.handler=function(b){if(this===b.target||!(/textarea|select/i.test(b.target.nodeName)||a.hotkeys.options.filterTextInputs&&-1<a.inArray(b.target.type,a.hotkeys.textAcceptingInputTypes))){var n=a.hotkeys.specialKeys[b.keyCode],g=String.fromCharCode(b.which).toLowerCase(),l="",h={};a.each(["alt","ctrl","meta","shift"],
function(a,c){b[c+"Key"]&&n!==c&&(l+=c+"+")});l=l.replace("alt+ctrl+meta+shift","hyper");n&&(h[l+n]=!0);g&&(h[l+g]=!0,h[l+a.hotkeys.shiftNums[g]]=!0,"shift+"===l&&(h[a.hotkeys.shiftNums[g]]=!0));for(var g=0,p=e.length;g<p;g++)if(h[e[g]])return c.apply(this,arguments)}}}}a.hotkeys={version:"0.8",specialKeys:{8:"backspace",9:"tab",10:"return",13:"return",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"capslock",27:"esc",32:"space",33:"pageup",34:"pagedown",35:"end",36:"home",37:"left",38:"up",39:"right",
40:"down",45:"insert",46:"del",59:";",61:"=",96:"0",97:"1",98:"2",99:"3",100:"4",101:"5",102:"6",103:"7",104:"8",105:"9",106:"*",107:"+",109:"-",110:".",111:"/",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",121:"f10",122:"f11",123:"f12",144:"numlock",145:"scroll",173:"-",186:";",187:"=",188:",",189:"-",190:".",191:"/",192:"`",219:"[",220:"\\",221:"]",222:"'"},shiftNums:{"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(",0:")","-":"_","=":"+",";":": ",
"'":'"',",":"<",".":">","/":"?","\\":"|"},textAcceptingInputTypes:"text password number email url range date month week time datetime datetime-local search color tel".split(" "),options:{filterTextInputs:!0}};a.each(["keydown","keyup","keypress"],function(){a.event.special[this]={add:c}})})(this.jQuery);(function(a,c,b){function d(a){var c={},d=/^jQuery\d+$/;b.each(a.attributes,function(a,b){b.specified&&!d.test(b.name)&&(c[b.name]=b.value)});return c}function e(a,c){var d=b(this);if(this.value==d.attr("placeholder")&&d.hasClass("placeholder"))if(d.data("placeholder-password")){d=d.hide().next().show().attr("id",d.removeAttr("id").data("placeholder-id"));if(!0===a)return d[0].value=c;d.focus()}else this.value="",d.removeClass("placeholder"),this==n()&&this.select()}function f(){var a,c=b(this),f=
this.id;if(""==this.value){if("password"==this.type){if(!c.data("placeholder-textinput")){try{a=c.clone().attr({type:"text"})}catch(g){a=b("<input>").attr(b.extend(d(this),{type:"text"}))}a.removeAttr("name").data({"placeholder-password":c,"placeholder-id":f}).bind("focus.placeholder",e);c.data({"placeholder-textinput":a,"placeholder-id":f}).before(a)}c=c.removeAttr("id").hide().prev().attr("id",f).show()}c.addClass("placeholder");c[0].value=c.attr("placeholder")}else c.removeClass("placeholder")}
function n(){try{return c.activeElement}catch(a){}}var g="[object OperaMini]"==Object.prototype.toString.call(a.operamini),l="placeholder"in c.createElement("input")&&!g,g="placeholder"in c.createElement("textarea")&&!g,h=b.fn,p=b.valHooks,k=b.propHooks;l&&g?(h=h.placeholder=function(){return this},h.input=h.textarea=!0):(h=h.placeholder=function(){this.filter((l?"textarea":":input")+"[placeholder]").not(".placeholder").bind({"focus.placeholder":e,"blur.placeholder":f}).data("placeholder-enabled",
!0).trigger("blur.placeholder");return this},h.input=l,h.textarea=g,h={get:function(a){var c=b(a),d=c.data("placeholder-password");return d?d[0].value:c.data("placeholder-enabled")&&c.hasClass("placeholder")?"":a.value},set:function(a,c){var d=b(a),g=d.data("placeholder-password");if(g)return g[0].value=c;if(!d.data("placeholder-enabled"))return a.value=c;""==c?(a.value=c,a!=n()&&f.call(a)):d.hasClass("placeholder")?e.call(a,!0,c)||(a.value=c):a.value=c;return d}},l||(p.input=h,k.value=h),g||(p.textarea=
h,k.value=h),b(function(){b(c).delegate("form","submit.placeholder",function(){var a=b(".placeholder",this).each(e);setTimeout(function(){a.each(f)},10)})}),b(a).bind("beforeunload.placeholder",function(){b(".placeholder").each(function(){this.value=""})}))})(this,document,jQuery);function assert(a,c){if(!a)throw Error(c||"Assertion failed");}jQuery.fn.shuffle=function(){for(var a,c=0;c<this.length;c++)a=Math.floor(Math.random()*this.length),$(this[c]).before($(this[a]));return this};function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}String.prototype.capitalize=function(){return this.charAt(0).toUpperCase()+this.slice(1)};
function randomSubset(a,c,b){for(var d=[],e=0;e<a.length;e++)0>c.indexOf(a[e])&&d.push(a[e]);shuffle(d);a=b-c.length;b=[];0<a&&(b=d.slice(0,a));b=b.concat(c);shuffle(b);return b}function randomElement(a){return a[Math.floor(Math.random()*a.length)]}function randomElementExcept(a,c){for(var b=[],d=0;d<a.length;d++)0>c.indexOf(a[d])&&b.push(a[d]);return randomElement(b)}
function LapTimer(){this.curr_time=this.start_time=new Date;this.start=function(){this.curr_time=this.start_time=new Date};this.lap=function(){var a=new Date,c=a-this.curr_time;this.curr_time=a;return c};this.lap_extra=function(){var a=this.curr_time-this.start_time,c=new Date-this.curr_time;this.curr_time=new Date;return a+";"+c};this.start_ms=function(){return this.start_time.getTime()/1E3}}
function InteractionTimer(){this.curr_time=this.s_time=new Date;this.started=!1;this.num_touches=0;this.touch=function(){var a=new Date;this.started||(this.s_time=a,this.started=!0);this.curr_time=a;this.num_touches++};this.start_time=function(){return this.started?this.s_time.getTime()/1E3:-1};this.activated=function(){return this.started};this.elapsed=function(){return this.curr_time-this.s_time};this.touches=function(){return this.num_touches};this.dump=function(){return[this.start_time()+";"+
this.elapsed()]}}
function GeneralTimer(a,c,b){this.start_time=new Date;this.num_ms=1E3*a;this.active=!1;this.last_remaining_time=0;this.expired=function(){return this.active&&new Date-this.start_time>this.num_ms};this.start=function(){this.start_time=new Date;0<=this.num_ms?(this.active=!0,c(),this.loop()):$("#seconds_left").html("No time limit.")};this.stop=function(){this.active=!1;$("#seconds_left").html("")};this.loop=function(){if(this.active){var a=this.num_ms-(new Date-this.start_time);if(0<a){var c=0,c=1E3>
this.num_ms?(Math.round(a/1E3*10)/10).toFixed(1):(Math.round(a/1E3*2)/2).toFixed(1);c!=this.last_remaining_time&&(this.last_remaining_time=c,$("#seconds_left").html("<b>"+c+"</b> seconds left"));var f=this;setTimeout(function(){f.loop()},20)}else $("#seconds_left").html("<b>Time's up!</b>"),$("#errors").html(""),b()}}}function randomIntFromInterval(a,c){return Math.floor(Math.random()*(c-a+1)+a)}function objectBoolean(){this.value=!1}function objectInteger(){this.value=0}
function randomTextReplacer(){$("input[name]").each(function(){$(this).attr("name",$(this).attr("name").replace(RegExp("#RND[0-9]*#","g"),""))});$("input[id]").each(function(){$(this).attr("id",$(this).attr("id").replace(RegExp("#RND[0-9]*#","g"),""))});$("textarea[name]").each(function(){$(this).attr("name",$(this).attr("name").replace(RegExp("#RND[0-9]*#","g"),""))});$("textarea[id]").each(function(){$(this).attr("id",$(this).attr("id").replace(RegExp("#RND[0-9]*#","g"),""))})}
jQuery.fn.getSelectionStart=function(){if(0==this.lengh)return-1;input=this[0];var a=input.value.length;input.createTextRange?(a=document.selection.createRange().duplicate(),a.moveEnd("character",input.value.length),a=input.value.lastIndexOf(a.text)):"undefined"!=typeof input.selectionStart&&(a=input.selectionStart);return a};
jQuery.fn.setSelection=function(a,c){if(0==this.lengh)return this;input=this[0];if(input.createTextRange){var b=input.createTextRange();b.collapse(!0);b.moveEnd("character",c);b.moveStart("character",a);b.select()}else input.setSelectionRange&&(input.focus(),input.setSelectionRange(a,c));return this};jQuery.fn.setCursorPosition=function(a){return 0==this.lengh?this:$(this).setSelection(a,a)};jQuery.fn.getCursorPosition=function(){return 0==this.lengh?-1:$(this).getSelectionStart()};
function getURIParam(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(location.search);return null===a?"":decodeURIComponent(a[1].replace(/\+/g," "))}jQuery.support.cors=!0;var PT={order:[],practice_ids:[],order_start_fns:[],order_end_fns:[],order_index:0,next_timings:[],next_timer:new LapTimer,interaction_timers:{},question_timers:{},is_completed:!1,is_showing_modal:!1,completion_fns:[],initialization_fns:{},initialization_bools:{},general_timers:{},window_focus:[],window_focuses:[],window_blur_time:new Date,window_load_time:new Date,completion_arrays:{},is_prepared:!1,exp_name:"Untitled",resetVariables:function(a){this.order=[];this.practice_ids=[];this.order_start_fns=
[];this.order_end_fns=[];this.order_index=0;this.next_timings=[];this.next_timer=new LapTimer;this.interaction_timers={};this.question_timers={};this.is_showing_modal=this.is_completed=!1;this.completion_fns=[];this.initialization_fns={};this.initialization_bools={};this.general_timers={};this.window_focus=[];this.window_focuses=[];this.window_blur_time=new Date;this.window_load_time=new Date;this.completion_arrays={};this.is_prepared=!1;this.exp_name=a},addPage:function(a,c,b){a="object"==typeof a?
a.attr("id"):a;c="undefined"!==typeof c?c:function(){};b="undefined"!==typeof b?b:function(){return!0};$("#"+a).html();assert(0>this.order.indexOf(a),"Page Id For "+a+" Exists!");this.order.push(a);this.order_start_fns.push(c);this.order_end_fns.push(b)},addPracticeId:function(a){this.practice_ids.push(a)},remoteSave:function(){$(":input").removeAttr("disabled");this.completeTaskFinally()},completeTaskFinally:function(){this.is_completed=!0;$("#submitButton").val("Submit").removeAttr("disabled");
$("#submitButton").click(function(){$(this).attr("disabled","disabled").val("Submitting...");$("form").submit()})},completeTask:function(){var a=/^[a-zA-Z0-9-_]+$/;$("input, textarea").each(function(){"undefined"!=typeof $(this).attr("name")&&-1==$(this).attr("name").search(a)&&assert(!1,"Invalid Input: "+$(this).attr("name"));"undefined"!=typeof $(this).attr("id")&&-1==$(this).attr("id").search(a)&&assert(!1,"Invalid Input: "+$(this).attr("id"))});for(var c in this.interaction_timers){var b='<input type="hidden" id="'+
c+'_timer" name="'+c+'_timer" value="'+this.interaction_timers[c].start_time()+"|"+this.interaction_timers[c].elapsed()+'">';$("#hidden_questions").append($(b))}for(c in this.general_timers)b='<input type="hidden" id="'+c+'_gtimer" name="'+c+'_gtimer" value="'+this.general_timers[c].dump().join("|")+'">',$("#hidden_questions").append($(b));for(var d in this.completion_arrays)b='<input type="hidden" id="'+d+'" name="'+d+'" value="'+this.completion_arrays[d].join("|")+'">',$("#hidden_questions").append($(b));
$("#order").val(this.order.join("|"));$("#start_timing").val(this.next_timer.start_ms());$("#next_timings").val(this.next_timings.join("|"));$("#window_focuses").val(this.window_focuses.join("|"));$("#practice_ids").val(this.practice_ids.join("|"));c=[];for(b=0;b<this.order.length;b++)q_id=this.order[b],"undefined"!=typeof this.question_timers[q_id]?c.push(this.question_timers[q_id].num_ms):c.push(-1);$("#time_limits").val(c.join("|"));$("#browser_info").val(navigator.userAgent);for(b=0;b<this.completion_fns.length;b++)this.completion_fns[b]();
$("#btn-next").hide();$("#submitButton").show().val("Please wait...").attr("disabled","disabled");this.remoteSave()},check_and_start:function(a){this.initialization_bools[a]=!0;for(var c in this.initialization_bools)if(!this.initialization_bools[c])return;$("#btn-next").removeAttr("disabled");$("#errors").html("");this.next_timer.start()},add_initialization_fn:function(a,c){this.initialization_fns[a]=c;this.initialization_bools[a]=!1},set_ip_address:function(a){$("#ip_address").val(a)},prepare:function(a){PT.resetVariables(a);
var c="#container form .instructions_start .instructions .base_q .end_comments".split(" ");for(a=0;a<c.length;a++)assert(1==$(c[a]).length,"Missing Element / Multiple Elements: "+c[a]);c="#questions #hidden_questions #bot-bar #seconds_left #errors #btn-next".split(" ");for(a=0;a<c.length;a++)assert(0==$(c[a]).length,"You can't use the reserved element with selector: "+c[a]);$("#container").prepend($('<div class="row"><div class="col-md-12 top-bar"></div></div>'));a='<div id="questions"></div><div class="row" id="bot-bar"><div class="col-md-12 bottom-bar" id="bar_bottom">';
a+='<div class="pull-left" style="padding: 8px;"><span id="seconds_left">&nbsp;</span></div>';a+='<span id="errors">Loading...</span>&nbsp;';a+='<input type="button" class="btn btn-lg btn-primary" id="btn-next" disabled="disabled" value="Next">';a+='<input type="button" id="submitButton" value="Submit" class="btn btn-lg btn-success" />';a+="</div></div>";a+='<div id="hidden_questions"></div>';$("#container").append($(a));c="order start_timing next_timings time_limits window_focuses practice_ids ip_address browser_info".split(" ");
for(a=0;a<c.length;a++)$r=$('<input type="hidden" name="'+c[a]+'" id="'+c[a]+'" value="">'),$("#hidden_questions").append($r);a=$(".instructions_start").addClass("row question").attr("id","instructions_start").detach();$("#questions").append(a);PT.addPage(a.attr("id"));this.$instructions=$(".instructions").addClass("row question").detach();this.$instructions_practice=$(".instructions_practice").addClass("row question").detach();this.$base_q=$(".base_q").addClass("row question").detach();this.$end=
$(".end_comments").addClass("row question").attr("id","end_comments").detach();this.is_prepared=!0},build_questions:function(a,c){var b=0,d=1,e={},f=a.time_limits;shuffle(f);var n=a.num_reps;f.unshift(a.practice_time_limit);n.unshift(a.practice_num_reps);assert(f.length==n.length,"# of provided time_limits must match # of provided num_reps.");assert(n.reduce(function(a,b){return a+b})<=c.length,"Insufficient # of questions provided for the # of repetitions desired.");for(var g=0;g<f.length;g++){var l=
f[g],h=0==g,p=this.$instructions.clone(),k=p.html(),k=h?k.replace(RegExp("#PRACTICE_STRING#","g"),"(Practice)"):k.replace(RegExp("#PRACTICE_STRING#","g"),""),k=k.replace(RegExp("#TIME_LIMIT#","g"),l),k=-1==l?k.replace(RegExp("#TIME_LIMIT_STRING#","g"),"no time limit"):k.replace(RegExp("#TIME_LIMIT_STRING#","g"),"up to "+l+" seconds"),k=k.replace(RegExp("#NUM_REPS#","g"),n[g]);p.html(k);p.attr("id","q"+d+"_ins");$("#questions").append(p);p.hide();PT.addPage(p.attr("id"));for(p=0;p<n[g];p++){k=c[b++];
assert("ID"in k,'Every question must have a field called "ID".');assert(0<k.ID.toString.length,"Every question ID must be non-empty.");assert(!(k.ID in e),"Every question ID must be unique.");e[k.ID]=!0;var m=this.$base_q.clone(),q=m.html(),r;for(r in k)q=q.replace(new RegExp("#"+r+"#","g"),k[r]);m.html(q);m.find("input").each(function(){assert("eta_id"!=$(this).attr("name"),'You can\'t name a form element "eid".');$(this).attr("name","q"+d+"_"+$(this).attr("name"));$(this).data("input_id",$(this).attr("name"))});
m.attr("id","q"+d+"_box");$id_field=$('<input type="hidden" name="q'+d+'_eid" value="'+k.ID+'">');m.append($id_field);$("#questions").append(m);m.hide();k=m.attr("id");h&&PT.addPracticeId(k);PT.addPage(k,function(a){return function(){PT.question_timers[a].start()}}(k),function(a,b,c){return function(){var b=!1,c={};$("#"+a+" :input").each(function(){"radio"==$(this).attr("type")?c[$(this).attr("name")]=!0:0==$(this).val().length?($(this).addClass("text-error"),$("#errors").html("Did you fill out everything?"),
b=!0):$(this).removeClass("text-error")});for(input_radio in c)0==$("input[name="+input_radio+"]:checked").length&&($("#errors").html("Did you select an answer?"),b=!0);if(b&&!PT.question_timers[a].expired())return!1;PT.question_timers[a].stop();$("#errors").html("");return!0}}(k,d,h));PT.question_timers[k]=new GeneralTimer(l,function(){},function(a){return function(){$("#"+a+" :input").attr("disabled","disabled");$("#"+a+" .radio").addClass("disabled")}}(k));d++}}$("#questions").append(this.$end);
this.$end.hide();PT.addPage(this.$end.attr("id"))},initialize:function(a,c){assert(this.is_prepared,"Call PT.prepare before calling PT.initialize.");var b=this;assert(b.order.length==b.order_start_fns.length&&b.order.length==b.order_end_fns.length,"Orders don't match");for(var d="btn-next submitButton errors order start_timing next_timings time_limits seconds_left window_focuses practice_ids browser_info".split(" "),e=0;e<d.length;e++)assert(1==$("#"+d[e]).length,"Missing form element: "+d[e]);d=
["time_limits","num_reps","practice_time_limit","practice_num_reps"];for(e=0;e<d.length;e++)assert(d[e]in a,"Missing key in question metadata: "+d[e]);this.build_questions(a,c);randomTextReplacer();this.window_load_time=new Date;this.window_focuses.push(this.window_load_time.getTime()/1E3);$(window).on({"focus.visibility":function(){b.window_focus.push(b.window_blur_time-b.window_load_time+","+(new Date-b.window_blur_time))},"blur.visibility":function(){b.window_blur_time=new Date}});$(":input:not([type=hidden])").each(function(){var a=
$(this).data("input_id");"undefined"!=typeof a&&(b.interaction_timers[a]=new InteractionTimer,$(this).focus(function(){b.interaction_timers[a].touch()}).keydown(function(){b.interaction_timers[a].touch()}))});0<$("img").length?this.add_initialization_fn("images",function(){$("#container").imagesLoaded(function(){b.check_and_start("images")})}):this.check_and_start("images");for(var f in this.initialization_fns)this.initialization_fns[f]();$("#btn-next").click(function(){b.order_index!=b.order.length-
1&&b.order_end_fns[b.order_index]()&&($("#"+b.order[b.order_index]).hide(),b.order_index++,$("#"+b.order[b.order_index]).show(),b.order_start_fns[b.order_index](),b.next_timings.push(b.next_timer.lap()),b.window_focuses.push(b.window_focus.join(";")),b.window_focus=[],$("#btn-next").blur(),b.order_index==b.order.length-1&&b.completeTask())});$(document).bind("keydown","shift+n",function(){$("#btn-next").click()});$("input, textarea").placeholder();"ASSIGNMENT_ID_NOT_AVAILABLE"==getURIParam("assignmentId")&&
(e='<div class="hit_preview"><div class="hit_preview_inner">Your work will not be saved until you accept this HIT.</div></div>',$("#container").append($(e)))}};